language: node_js
node_js:
  - "0.10"
before_install:
  - cd cv
  - npm install -g grunt-cli
install: npm install
before_script:
  - cd external/qooxdoo
  - npm install
  - grunt setup
  - cd ../../cv
  - grunt build
